-- Esquema de la tabla Principal para Supabase
CREATE TABLE IF NOT EXISTS "Principal" (
  id SERIAL PRIMARY KEY,
  nombre_apellido TEXT NOT NULL,
  email TEXT NOT NULL,
  edad INTEGER NOT NULL,
  genero TEXT NOT NULL,
  peso_kg NUMERIC NOT NULL,
  altura_m NUMERIC NOT NULL,
  vo2max NUMERIC NOT NULL,
  vo2max_device TEXT NOT NULL,
  fc_max INTEGER NOT NULL,
  fc_max_device TEXT NOT NULL,
  rhr INTEGER NOT NULL,
  distancia_competencia_km NUMERIC NOT NULL,
  tiempo_competencia TEXT NOT NULL,
  kms_semanales NUMERIC NOT NULL,
  kms_max_carga NUMERIC NOT NULL,
  kms_por_sesion NUMERIC NOT NULL,
  anos_running INTEGER NOT NULL,
  distancia_max_sesion NUMERIC NOT NULL,
  mejor_10k_time TEXT NOT NULL,
  ritmo_fondo NUMERIC NOT NULL,
  ritmo_200m NUMERIC NOT NULL,
  proximo_objetivo TEXT NOT NULL,
  fecha_objetivo DATE NOT NULL,
  evento_similar TEXT NOT NULL,
  info_relevante TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
